### ISSUE TITLE
Add an upvote and downvote system

### ISSUE THREAD

**Issue by blueweaver** [ChicoState/Gruvest#3]
As a content creator, I want to be able to have a high rank, so that I can better promote my pitches

**Comment by 0hana** [comment]
"As a content creator, ..." Are you referring to a "pitcher"? On the matter of "Add an upvote and downvote system", why? Are pitches ranked by their sales pitch and charisma of the "pitcher", or the (un)successful track record of a pitcher which can be objectively verified in terms of rate of returns to "catchers"? Please clarify and explain.
