### ISSUE TITLE
user page

### ISSUE THREAD

**Issue by blueweaver** [ChicoState/Gruvest#5]
As a user, I want to be able to have a record of my pitches and catches, so that I can show my friends the investments that I have made.

**Comment by 0hana** [comment]
This is vague. What is "my post"? In this user story, are you representing the "pitcher", and your post is your investment strategy "pitch"--and thus the record is a hyperlink to the pitch page--or perhaps are you a "catcher", and you want to show a profile stats page detailing pitches you've invested in? "I want to be able to have a record of my post" on it's own almost feels like a hyperlink to a comment made on a pitch page. Please clarify.
